### ISSUE TITLE
hammer.lol or comma.ai?

### ISSUE THREAD

**Issue by TheOGUmar** [geohot/tinyxxx#1]
George do you want to keep the website design like how it currently is or make it visually better like [comma's](https://comma.ai/)? Let me know so my pull requests dont go to waste..

**Comment by yochem** [comment]
I think the design is quite in line with the goal of the tinygrad project ;)

**Comment by TheOGUmar** [comment]
> I think the design is quite in line with the goal of the tinygrad project ;)

Yeah the design maybe in line with the tiny corp aswell

**Comment by catasaurus** [comment]
lol just spend like two hours on improving it then read this :(
